name: OZIP Decrypter

on:
#  release:
#    types: [published]
#  push:
#    branches:
#      - master
#    paths:
#      - '.config'
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]

env:
  FIRMWARE_LINK: https://download.c.realme.com/osupdate/CPH1861EX_11_OTA_0290_all_hKCRId6dsKkB.ozip
  FIRMWARE_NAME: CPH1861EX_11_OTA_0290_all_hKCRId6dsKkB.ozip
  FIRMWARE_ZIP_NAME: CPH1861-5.2-OTA
  TZ: Asia/Kolkata

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
       - name: Checkout
         uses: actions/checkout@master
         
       - name: Downloading Ozip Now.. 
         run: |
            sudo -E apt-get -qq update
            sudo apt install aria2 expect -y
            aria2c $FIRMWARE_LINK
             
       - name: Decrypting Ozip Now
         run: |
             sudo -E apt-get -qq update
             sudo apt-get install python-pip
             sudo -H pip install --upgrade pip
             sudo -H pip install setuptools wheel docopt pycryptodome zip
             wget https://raw.githubusercontent.com/techyminati/oppo_ozip_decrypt/master/ozipdecrypt.py
             sudo python ozipdecrypt.py $FIRMWARE_NAME
             zip -r $FIRMWARE_ZIP_NAME.zip ./out/*

       - name: Upload Decrypted Zip
         run: |
              curl -sL https://git.io/file-transfer | sh ; sudo chmod a+x transfer
             ./transfer wet ./*.zip
              
